CREATE TABLE public.firm (
	firm_id int8 NOT NULL GENERATED ALWAYS AS IDENTITY,
	title varchar NOT NULL,
	description varchar NULL,
	discount numeric NOT NULL,
	CONSTRAINT firm_pk PRIMARY KEY (firm_id)
);

CREATE TABLE public.series (
	series_id int8 NOT NULL GENERATED ALWAYS AS IDENTITY,
	title varchar NOT NULL,
	description varchar NULL,
	firm_id int4 NOT NULL,
	discount numeric NOT NULL,
	CONSTRAINT series_pk PRIMARY KEY (series_id),
	CONSTRAINT series_fk FOREIGN KEY (firm_id) REFERENCES public.firm(firm_id)
);

CREATE TABLE public.category (
	category_id int8 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	title varchar NOT NULL,
	description varchar NULL,
	discount numeric NOT NULL,
	CONSTRAINT category_pk PRIMARY KEY (product_id)
);

CREATE TABLE public.product (
	product_id int8 NOT NULL GENERATED ALWAYS AS IDENTITY,
	category_id int8 NOT NULL,
	series_id int8 NULL,
	title varchar NOT NULL,
	description varchar NULL,
	"cost" money NOT NULL,
	delivery_time interval NOT NULL,
	discount numeric NOT NULL,
	CONSTRAINT product_pk PRIMARY KEY (product_id),
	CONSTRAINT product_fk FOREIGN KEY (product_id) REFERENCES public.category(product_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT product_fk_1 FOREIGN KEY (series_id) REFERENCES public.series(series_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE public.photo (
	photo_id int8 NOT NULL GENERATED ALWAYS AS IDENTITY,
	product_id int8 NULL,
	category_id int8 NULL,
	series_id int8 NULL,
	firm_id int8 NULL,
	"name" varchar NOT NULL,
	CONSTRAINT photo_pk PRIMARY KEY (photo_id),
	CONSTRAINT photo_fk FOREIGN KEY (product_id) REFERENCES public.product(product_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT photo_fk_1 FOREIGN KEY (product_id) REFERENCES public.category(product_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT photo_fk_2 FOREIGN KEY (series_id) REFERENCES public.series(series_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT photo_fk_3 FOREIGN KEY (firm_id) REFERENCES public.firm(firm_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE public."user" (
	user_id int8 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	tg_id varchar NOT NULL,
	"name" varchar NOT NULL,
	adress varchar NULL,
	telephone varchar NULL,
	email varchar NULL,
	tg_ref varchar NULL,
	"admin" bool NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (user_id)
);

CREATE TABLE public."order" (
	user_id int8 NOT NULL,
	card_id int8 NOT NULL,
	finished bool NOT NULL,
	order_id int8 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	price money NOT NULL,
	CONSTRAINT order_pk PRIMARY KEY (order_id),
	CONSTRAINT order_fk FOREIGN KEY (user_id) REFERENCES public."user"(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE public.order_product (
	order_product_id int8 NOT NULL GENERATED ALWAYS AS IDENTITY,
	order_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	product_id int8 NOT NULL,
	quantity int4 NOT NULL,
	CONSTRAINT order_product_pk PRIMARY KEY (order_product_id),
	CONSTRAINT order_product_fk FOREIGN KEY (order_id) REFERENCES public."order"(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT order_product_fk_1 FOREIGN KEY (product_id) REFERENCES public.product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
);