import './globals.scss'
import type { Metadata } from 'next'
import Providers from '@/providers/Providers'
import { roboto } from '@/theme/fonts'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='ru'>
			<Providers>
				<body className={roboto.className}>{children}</body>
			</Providers>
		</html>
	)
}
